name: CI for Python
'on':
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu_latest
    steps:
      - name: checout code
        uses: actions/checkout@v3
      - name: setup python
        uses: actions/setup-pytho@v3
        with:
          python-version: '3.10'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install flake8 pytest
          if[ -f requirements.txt ];
            then pip install requirement.txt;
          fi
      - name: lint with flake8
        run: >
          flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics

          flake8 . --count --exit-zero -max-complexity=10 --max-line-lenght=127
          --statistics
      - name: test with pytest
        run: |
          python -m pytest --verbose --junit-xml=junit.xml
      - name: publish test report
        uses: mikepenz/action-junit-report@v3
        if: success() || failure()
        with:
          report_paths: '**/junit.xml'
          detailed_summary: true
          include_passed: true
     
